version: "3.8"
services:
  app:
    build:
      context: target
      dockerfile: ../Dockerfile
    restart: always
    ports:
      - 8001:8001
      - 8002:8002
      - 8003:8003
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Moscow
      - SPRING_JPA_DATABASE=POSTGRESQL
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQL10Dialect
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
    env_file:
      - db.env
